#!/usr/bin/env bash
#displays when process killed
trap 'echo "I am invincible!!!"' SIGTERM

# Display "To infinity and beyond" indefinitely with a 2-second delay
while true
do
    echo "To infinity and beyond"
    sleep 2
done
