#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ]; do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]; do
        echo "$minute"
        ((minute++))
    done
    ((hour++))
done


#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hour=0
minute=1

while true; do
    echo "Hour: $hour"
    echo "$minute"
    ((minute++))
    if [ $minute -gt 59 ]; then
        ((hour++))
        minute=1
    fi
    if [ $hour -gt 12 ]; then
        break
    fi
done
